//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WMS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///    &lt;head&gt;
        ///         &lt;style type=&quot;text/css&quot;&gt;
        ///             body {
        ///                font-family:Arial;
        ///                line-height:15px;
        ///                font-size:12px;
        ///             }
        ///             .table, .table tr td, .table tr th {
        ///                border-collapse:collapse;
        ///                border: 1px solid black;
        ///             }
        ///         &lt;/style&gt;
        ///    &lt;/head&gt;
        ///    &lt;body&gt;
        ///        &lt;strong&gt;ACTUAL STOCKS REPORT&lt;/strong&gt;&lt;br /&gt;
        ///        [run_datetime]
        ///       
        ///        &lt;br /&gt; &lt;br [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string actualstockreport {
            get {
                return ResourceManager.GetString("actualstockreport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///    &lt;head&gt;
        ///         &lt;style type=&quot;text/css&quot;&gt;
        ///             body {
        ///                font-family:Arial;
        ///                line-height:15px;
        ///                font-size:12px;
        ///             }
        ///             .table, .table tr td, .table tr th {
        ///                border-collapse:collapse;
        ///                border: 1px solid black;
        ///             }
        ///         &lt;/style&gt;
        ///    &lt;/head&gt;
        ///	&lt;body&gt; 
        ///		&lt;strong&gt;Bad Stock Declaration #&lt;/strong&gt; (issued on save) 
        ///		&lt;br/&gt;
        ///		&lt;strong&gt;Declared by:&lt;/strong&gt; [de [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bad_stock_declaration_form {
            get {
                return ResourceManager.GetString("bad_stock_declaration_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///    &lt;head&gt;
        ///         &lt;style type=&quot;text/css&quot;&gt;
        ///             body {
        ///                font-family:Arial;
        ///                line-height:15px;
        ///                font-size:12px;
        ///             }
        ///             .table, .table tr td, .table tr th {
        ///                border-collapse:collapse;
        ///                border: 1px solid black;
        ///             }
        ///         &lt;/style&gt;
        ///    &lt;/head&gt;
        ///    &lt;body&gt;
        ///        &lt;strong&gt;PICKLIST #&lt;/strong&gt; (issued on save) &lt;br /&gt;
        ///        &lt;strong&gt;CASEBREAK #&lt;/strong&gt; (issue [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string case_break_picklist {
            get {
                return ResourceManager.GetString("case_break_picklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        body {
        ///            font-family: Arial;
        ///            line-height: 15px;
        ///            font-size: 12px;
        ///        }
        ///
        ///        .table, .table tr td, .table tr th {
        ///            border-collapse: collapse;
        ///            border: 1px solid black;
        ///        }
        ///    &lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;strong&gt;PUTAWAY #&lt;/strong&gt; (issued on save) &lt;br /&gt;
        ///    &lt;strong&gt;PICKLIST #&lt;/strong&gt; (issued on save picklist) &lt;br /&gt;
        ///    &lt;strong&gt;CASEBREAK #&lt;/strong&gt; (issu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string case_break_putaway {
            get {
                return ResourceManager.GetString("case_break_putaway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///    &lt;head&gt;
        ///         &lt;style type=&quot;text/css&quot;&gt;
        ///             body {
        ///                font-family:Arial;
        ///                line-height:15px;
        ///                font-size:12px;
        ///             }
        ///             .table, .table tr td, .table tr th {
        ///                border-collapse:collapse;
        ///                border: 1px solid black;
        ///             }
        ///         &lt;/style&gt;
        ///    &lt;/head&gt;
        ///    &lt;body&gt;
        ///        &lt;strong&gt;CASE BREAK #&lt;/strong&gt; (issued on save) &lt;br /&gt;
        ///        &lt;strong&gt;PICKLIST #&lt;/strong&gt; (issu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string case_break_report {
            get {
                return ResourceManager.GetString("case_break_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///    &lt;head&gt;
        ///         &lt;style type=&quot;text/css&quot;&gt;
        ///             body {
        ///                font-family:Arial;
        ///                line-height:15px;
        ///                font-size:12px;
        ///             }
        ///             .table, .table tr td, .table tr th {
        ///                border-collapse:collapse;
        ///                border: 1px solid black;
        ///             }
        ///         &lt;/style&gt;
        ///    &lt;/head&gt;
        ///	&lt;body&gt; 
        ///		&lt;strong&gt;Count Sheet #&lt;/strong&gt; (issued on save) 
        ///		&lt;br/&gt;
        ///		&lt;strong&gt;Counted by:&lt;/strong&gt; [counted_by]
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string declare_physical_count_report {
            get {
                return ResourceManager.GetString("declare_physical_count_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        body {
        ///            font-family: Arial;
        ///            line-height: 15px;
        ///            font-size: 12px;
        ///        }
        ///
        ///        .table, .table tr td, .table tr th {
        ///            border-collapse: collapse;
        ///            border: 1px solid black;
        ///        }
        ///    &lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;strong&gt;DISCREPANCY ID #&lt;/strong&gt; (issued on save) &lt;br /&gt;
        ///    [run_datetime]
        ///    &lt;br /&gt; &lt;br /&gt;
        ///
        ///    Approved From: [approved_from] &lt;br /&gt;
        ///    Approved  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string discrepancy_report {
            get {
                return ResourceManager.GetString("discrepancy_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///    &lt;head&gt;
        ///         &lt;style type=&quot;text/css&quot;&gt;
        ///             body {
        ///                font-family:Arial;
        ///                line-height:15px;
        ///                font-size:12px;
        ///             }
        ///             .table, .table tr td, .table tr th {
        ///                border-collapse:collapse;
        ///                border: 1px solid black;
        ///             }
        ///         &lt;/style&gt;
        ///    &lt;/head&gt;
        ///	&lt;body&gt; 
        ///		&lt;strong&gt;Diposal Pick List #&lt;/strong&gt; (issued on save) &lt;br/&gt;
        ///        [run_datetime]
        ///         &lt;br/&gt; &lt;br/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dispose_picklist_report {
            get {
                return ResourceManager.GetString("dispose_picklist_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///    &lt;head&gt;
        ///         &lt;style type=&quot;text/css&quot;&gt;
        ///             body {
        ///                font-family:Arial;
        ///                line-height:15px;
        ///                font-size:12px;
        ///             }
        ///             .table, .table tr td, .table tr th {
        ///                border-collapse:collapse;
        ///                border: 1px solid black;
        ///             }
        ///         &lt;/style&gt;
        ///    &lt;/head&gt;
        ///	&lt;body&gt; 
        ///		&lt;strong&gt;Pick List #&lt;/strong&gt; (issued on save) &lt;br/&gt;
        ///        [run_datetime]
        ///         &lt;br/&gt; &lt;br/&gt;
        ///		 &lt;h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string incomplete_picklist_report {
            get {
                return ResourceManager.GetString("incomplete_picklist_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///    &lt;head&gt;
        ///         &lt;style type=&quot;text/css&quot;&gt;
        ///             body {
        ///                font-family:Arial;
        ///                line-height:15px;
        ///                font-size:12px;
        ///             }
        ///             .table, .table tr td, .table tr th {
        ///                border-collapse:collapse;
        ///                border: 1px solid black;
        ///             }
        ///         &lt;/style&gt;
        ///    &lt;/head&gt;
        ///	&lt;body&gt; 
        ///		&lt;strong&gt;  Order Cancellation #&lt;/strong&gt; (issued on save)  &lt;br/&gt;
        ///        Cancelled On: [cancelled_on]
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string order_cancel {
            get {
                return ResourceManager.GetString("order_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///    &lt;head&gt;
        ///         &lt;style type=&quot;text/css&quot;&gt;
        ///             body {
        ///                font-family:Arial;
        ///                line-height:15px;
        ///                font-size:12px;
        ///             }
        ///             .table, .table tr td, .table tr th {
        ///                border-collapse:collapse;
        ///                border: 1px solid black;
        ///             }
        ///         &lt;/style&gt;
        ///    &lt;/head&gt;
        ///	&lt;body&gt; 
        ///		&lt;strong&gt;Physical Count Calendar &lt;/strong&gt;  &lt;br/&gt;
        ///        [run_datetime]
        ///         &lt;br/&gt; &lt;br/&gt;
        ///		
        ///
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pc_calendar {
            get {
                return ResourceManager.GetString("pc_calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///    &lt;head&gt;
        ///         &lt;style type=&quot;text/css&quot;&gt;
        ///             body {
        ///                font-family:Arial;
        ///                line-height:15px;
        ///                font-size:12px;
        ///             }
        ///             .table, .table tr td, .table tr th {
        ///                border-collapse:collapse;
        ///                border: 1px solid black;
        ///             }
        ///         &lt;/style&gt;
        ///    &lt;/head&gt;
        ///	&lt;body&gt; 
        ///		&lt;strong&gt;Count Sheet #&lt;/strong&gt; (issued on save) 
        ///		&lt;br/&gt;
        ///		&lt;strong&gt;Counted by:&lt;/strong&gt; [counted_by]
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string physical_count_report {
            get {
                return ResourceManager.GetString("physical_count_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///    &lt;head&gt;
        ///         &lt;style type=&quot;text/css&quot;&gt;
        ///             body {
        ///                font-family:Arial;
        ///                line-height:15px;
        ///                font-size:12px;
        ///             }
        ///             .table, .table tr td, .table tr th {
        ///                border-collapse:collapse;
        ///                border: 1px solid black;
        ///             }
        ///         &lt;/style&gt;
        ///    &lt;/head&gt;
        ///	&lt;body&gt; 
        ///		&lt;strong&gt;Pick List #&lt;/strong&gt; (issued on save) &lt;br/&gt;
        ///        [run_datetime]
        ///         &lt;br/&gt; &lt;br/&gt;
        ///		 &lt;h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string picklist_report {
            get {
                return ResourceManager.GetString("picklist_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///    &lt;head&gt;
        ///         &lt;style type=&quot;text/css&quot;&gt;
        ///             body {
        ///                font-family:Arial;
        ///                line-height:15px;
        ///                font-size:12px;
        ///             }
        ///             .table, .table tr td, .table tr th {
        ///                border-collapse:collapse;
        ///                border: 1px solid black;
        ///             }
        ///         &lt;/style&gt;
        ///    &lt;/head&gt;
        ///	&lt;body&gt; 
        ///		&lt;strong&gt;Putaway ID:&lt;/strong&gt; (issued on save) &lt;br/&gt;
        ///        [run_datetime]
        ///         &lt;br/&gt; &lt;br/&gt;
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string putaway_report {
            get {
                return ResourceManager.GetString("putaway_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///    &lt;head&gt;
        ///         &lt;style type=&quot;text/css&quot;&gt;
        ///             body {
        ///                font-family:Arial;
        ///                line-height:15px;
        ///                font-size:12px;
        ///             }
        ///             .table, .table tr td, .table tr th {
        ///                border-collapse:collapse;
        ///                border: 1px solid black;
        ///             }
        ///             P{
        ///                 font-family:Courier New;
        ///                 font-size:12px;
        ///                 font-weight:bold;
        ///             }
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string receiving_report {
            get {
                return ResourceManager.GetString("receiving_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///    &lt;head&gt;
        ///         &lt;style type=&quot;text/css&quot;&gt;
        ///             body {
        ///                font-family:Arial;
        ///                line-height:15px;
        ///                font-size:12px;
        ///             }
        ///             .table, .table tr td, .table tr th {
        ///                border-collapse:collapse;
        ///                border: 1px solid black;
        ///             }
        ///         &lt;/style&gt;
        ///    &lt;/head&gt;
        ///	&lt;body&gt; 
        ///		&lt;strong&gt;Warehouse Releasing Report #&lt;/strong&gt; (issued on save) &lt;br/&gt;
        ///        [run_datetime]
        ///         &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string releasing_report {
            get {
                return ResourceManager.GetString("releasing_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///    &lt;head&gt;
        ///         &lt;style type=&quot;text/css&quot;&gt;
        ///             body {
        ///                font-family:Arial;
        ///                line-height:15px;
        ///                font-size:12px;
        ///             }
        ///             .table, .table tr td, .table tr th {
        ///                border-collapse:collapse;
        ///                border: 1px solid black;
        ///             }
        ///         &lt;/style&gt;
        ///    &lt;/head&gt;
        ///	&lt;body&gt; 
        ///		&lt;strong&gt; [variance] Resolution #&lt;/strong&gt; (issued on save)  &lt;br/&gt;
        ///        Resolved On: [run_datetime]
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string resolution_report {
            get {
                return ResourceManager.GetString("resolution_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap secrecy_icon {
            get {
                object obj = ResourceManager.GetObject("secrecy-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap wms_badge {
            get {
                object obj = ResourceManager.GetObject("wms_badge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
